[general]
live_config_reload = true
working_directory = "C:\\Users\\dobha"

[window]
decorations = "None"
opacity = 0.7
title = "Terminal"
dynamic_title = false
decorations_theme_variant = "Dark"
padding = { x = 5, y = 10 }

[font]
normal = { family = "BlexMono Nerd Font Mono", style = "Regular" }
size = 12

[colors]
cursor = { text = "#00ecff", cursor = "#ab3c7e" }

[colors.normal]
black = "#050505"
red = "#ff0000"
green = "#00ff00"
yellow = "#f5d105"
blue = "#0000ff"
magenta = "#ff00ea"
cyan = "#00ecff"
white = "#ffffff"

[cursor]
style = { shape = "Underline", blinking = "Off" }

[mouse]
hide_when_typing = true

[terminal]
shell = { program = "powershell", args = ["-nologo"] }
